# Generated by Django 3.2.18 on 2023-03-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('content', models.FileField(max_length=50, upload_to='')),
                ('mark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=50)),
                ('percentage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktu_id', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('photo', models.FileField(max_length=50, upload_to='')),
                ('house', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('certificate', models.FileField(max_length=300, upload_to='')),
                ('DEPARTMENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('DEPARTMENT', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROGRAM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.program')),
                ('SEMESTER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.semester')),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=50)),
                ('SUBJECT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='suspend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('FACULTY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.faculty')),
                ('PROGRAM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.program')),
                ('TIMETABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='subjectallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FACULTY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.faculty')),
                ('PROGRAM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.program')),
            ],
        ),
        migrations.CreateModel(
            name='studymaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(max_length=50, upload_to='')),
                ('SUBJECT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktu_id', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('photo', models.FileField(max_length=50, upload_to='')),
                ('house', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.batch')),
                ('DEPARTMENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.department')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.login')),
                ('SEMESTER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.semester')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.batch')),
                ('DEPARTMENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.department')),
                ('FACULTY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='specialclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('SUBJECT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('notification', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='internal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50)),
                ('ASSIGNMENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.assignment')),
                ('ATTENDANCE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.attendance')),
                ('EXAM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.exam')),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.student')),
                ('SUBJECT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.subject')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.login'),
        ),
        migrations.AddField(
            model_name='exam',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='SUBJECT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.subject'),
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=50)),
                ('STAFF', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.staff')),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='PROGRAM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.program'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='FACULTY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.faculty'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='SUBJECT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.subject'),
        ),
    ]
