# Generated by Django 3.2.18 on 2023-03-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='certificate',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
