# Generated by Django 3.2.18 on 2023-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0002_auto_20230310_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
