# Generated by Django 3.2.18 on 2023-03-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0005_program_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='SEMESTER',
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
