# Generated by Django 3.2.18 on 2023-03-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0006_auto_20230312_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='pname',
        ),
    ]
