# Generated by Django 3.2.18 on 2023-03-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0007_rename_name_program_pname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectallocation',
            name='PROGRAM',
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='SUBJECT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.subject'),
        ),
    ]
