# Generated by Django 3.2.18 on 2023-03-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0008_auto_20230312_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SEMESTER',
            field=models.IntegerField(default=1),
        ),
    ]
