# Generated by Django 3.2.18 on 2023-03-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0009_alter_student_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='SEMESTER',
            new_name='semester',
        ),
    ]
