# Generated by Django 3.2.18 on 2023-03-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0011_alter_login_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='event',
        ),
        migrations.AddField(
            model_name='calendar',
            name='clas',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='calendar',
            name='enddate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='calendar',
            name='startdate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='calendar',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='calendar',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
