# Generated by Django 3.2.18 on 2023-04-01 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0013_timetable_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='PROGRAM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.program'),
        ),
    ]
