# Generated by Django 3.2.18 on 2023-04-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0014_student_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=50)),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.student')),
            ],
        ),
    ]
