# Generated by Django 3.2.18 on 2023-04-10 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0015_substitution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitution',
            name='STUDENT',
        ),
        migrations.AddField(
            model_name='substitution',
            name='SUBJECT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.subject'),
        ),
    ]
