# Generated by Django 3.2.18 on 2023-04-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0017_substitution_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internal',
            name='ASSIGNMENT',
        ),
        migrations.RemoveField(
            model_name='internal',
            name='ATTENDANCE',
        ),
        migrations.RemoveField(
            model_name='internal',
            name='EXAM',
        ),
    ]
