# Generated by Django 3.2.18 on 2023-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0019_internal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=100)),
                ('end', models.CharField(default='', max_length=100)),
                ('text', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('bg', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
