# Generated by Django 3.2.18 on 2023-04-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0023_alter_medical_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='TIMETABLE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.timetable'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
