# Generated by Django 3.2.18 on 2023-05-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0024_auto_20230421_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignmentfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=50)),
                ('ASSIGNMENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.assignment')),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.student')),
            ],
        ),
    ]
