# Generated by Django 3.2.18 on 2023-05-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0026_auto_20230503_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='reply',
        ),
    ]
