# Generated by Django 3.2.18 on 2023-05-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0027_remove_chat_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='STAFF',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EdulinkApp.faculty'),
        ),
    ]
