# Generated by Django 3.2.18 on 2023-05-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdulinkApp', '0028_alter_chat_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='time',
        ),
    ]
